topopartner/urls.py
from django.urls import path
from . import views

app_name = "topopartner"

urlpatterns = [
    path("", views.view_landing, name="landing"),
    path("about", views.view_about, name="about"),
    path("routes", views.view_routes, name="routes"),
    path("recordings", views.view_recordings, name="recordings"),
    path("track/create", views.view_create_track, name="create_track"),
    path("track/upload", views.view_upload_track, name="upload_track"),
    path("track/<tid>", views.view_track, name="view_track"),
    path("track/<tid>/edit", views.view_edit_track, name="edit_track"),
    path("track/<tid>/elevate", views.view_elevate_track, name="elevate_track"),
    path("track/<tid>/smooth", views.view_smooth_track, name="smooth_track"),
    path("track/<tid>/download", views.view_download_track, name="download_track"),
    path("track/<tid>/download/gpx", views.view_download_track_gpx, name="download_track_gpx"),
    path("track/<tid>/download/stl", views.view_download_track_stl, name="download_track_stl"),
    path("track/<tid>/delete", views.view_delete_track, name="delete_track"),
    path("track/<tid>/points", views.view_track_points, name="track_points"),
    path("fit", views.view_fit, name="fit"),
    path("api/route/list", views.api_list_routes, name="api_list_routes"),
    path("api/route/get", views.api_get_route, name="api_get_route"),
    path("api/recording/post", views.api_post_recording, name="api_post_recording"),
]

topopartner/templates/topopartner/about.html
{% extends 'topopartner/layout/base.html' %}
{% load static %}

{% block main_content %}

<div class="h1">Topopartner</div>

<p>
    <b>Topopartner</b> is a Django application dedicated to topographic personal data management.
    Namely, it holds a database of <b>waypoints</b> and <b>tracks</b>.
    It offers a track edition interface, GPX exports, elevation profile plots, hike duration prediction, and more.
    It greatly relies on the
    <span class="highlight"><a href="https://leafletjs.com/">Leaflet</a></span>
    library,
    <span class="highlight"><a href="https://wiki.openstreetmap.org/wiki/OpenTopoMap">OpenTopoMap</a></span>
    maps, and
    <span class="highlight"><a href="https://www.gpsvisualizer.com/">GPS Visualizer</a></span>
    features.
</p>

<p>
    It is available on <a href="https://github.com/ychalier/topopartner">GitHub</a>.
    If you want to try it yourself, <a href="https://chalier.fr/">contact me</a> for a demo account.
</p>

{% endblock main_content %}

topopartner/templates/topopartner/create_track.html
{% extends 'topopartner/layout/base.html' %}
{% load static %}

{% block title %}Create track &mid; {{ block.super }}{% endblock title %}

{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'topopartner/css/map.css' %}">
{% endblock head %}

{% block main_content %}
<div class="h1">Create track</div>
<div class="columns">

    <div class="column col-8 col-sm-12">
        {% include 'topopartner/partials/map.html' %}
    </div>

    <div class="column col-4 col-sm-12">
        <div>
            <button id="buttonClearTrack" class="btn btn-primary" type="button" name="button">Clear track</button>
        </div>
        <div id="track_form">
            <div class="form-group">
                <label class="form-label" for="input-label">Label</label>
                <input class="form-input" id="input-label" type="text" name="label"  placeholder="Label*" />
            </div>
            <div class="form-group">
                <label class="form-label" for="input-comment">Comment</label>
                <textarea class="form-input" id="input-comment" name="comment" rows="8" cols="80" placeholder="Comment"></textarea>
            </div>

            <div class="form-group">
                <label class="form-switch">
                    <input id="input_public" type="checkbox" name="public" />
                    <i class="form-icon"></i> Make the track public
                </label>
            </div>
            <div class="form-group">
                <label class="form-switch">
                    <input id="input_route" type="checkbox" name="route" checked />
                    <i class="form-icon"></i> Make the track a route
                </label>
            </div>
        </div>
        <div>
            <button id="buttonSaveTrack" class="btn btn-primary" type="button" name="button">Save</button>
        </div>
    </div>
    <script type="text/javascript">
        mapWrapper.bindButtonClearTrack("buttonClearTrack");
        mapWrapper.bindButtonSaveTrack("buttonSaveTrack");
        mapWrapper.bindTrackForm("track_form");
    </script>
</div>
{% endblock main_content %}

topopartner/templates/topopartner/edit_track.html
{% extends 'topopartner/layout/base.html' %}
{% load static %}

{% block title %}Edit track &mid; {{ block.super }}{% endblock title %}

{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'topopartner/css/map.css' %}">
{% endblock head %}

{% block main_content %}

<h1>{{ track.label }}</h1>

<div class="columns">

    <div class="column col-8 col-sm-12">
        {% include 'topopartner/partials/map.html' %}
    </div>

    <div class="column col-4 col-sm-12">

        <div>
            {% if track.is_route %}
                <button class="btn btn-primary btn-sm" id="buttonClearTrack" type="button" name="button" title="Erase the track from the map">Clear</button>
            {% endif %}
            <a class="btn btn-primary btn-sm" href="{% url 'topopartner:delete_track' tid=track.id %}" title="Completely remove this track">Delete</a>
            <a class="btn btn-primary btn-sm" href="{% url 'topopartner:elevate_track' tid=track.id %}" title="Fetch and replace elevation data for this track">Fetch elevation</a>
            <button class="btn btn-primary btn-sm" onclick="showModal('modal-smooth-track')" title="Create a smooth version of this track">Smooth</button>
        </div>

        <div id="track_form">
            <div class="form-group">
                <label class="form-label" for="input-label">Label</label>
                <input class="form-input" type="text" name="label"  placeholder="Label*" id="input-label" />
            </div>
            <div class="form-group">
                <label class="form-label" for="input-comment">Comment</label>
                <textarea class="form-input" name="comment" rows="8" cols="80" placeholder="Comment" id="input-comment"></textarea>
            </div>
            <div class="form-group">
                <label class="form-switch">
                    <input id="input_public" type="checkbox" name="public" {% if track.public %}checked{% endif %} />
                    <i class="form-icon"></i> Make the track public
                </label>
            </div>
            <div class="form-group">
                <label class="form-switch">
                    <input id="input_route" type="checkbox" name="route" {% if track.is_route %}checked{% endif %} />
                    <i class="form-icon"></i> Make the track a route
                </label>
            </div>
            <button id="buttonSaveTrack" class="btn btn-primary" type="button" name="button">Save</button>
        </div>
    </div>

    <div class="modal" id="modal-smooth-track">
        <span class="modal-overlay" aria-label="Close" onclick="closeModal('modal-smooth-track')"></span>
        <div class="modal-container">
            <form method="post" action="{% url 'topopartner:smooth_track' tid=track.id %}">
                {% csrf_token %}
                <div class="modal-header">
                    <span onclick="closeModal('modal-smooth-track')" class="btn btn-clear float-right" aria-label="Close"></span>
                    <div class="modal-title h5">Smooth track</div>
                </div>
                <div class="modal-body">
                    <div class="content">
                        <div class="form-group">
                            <label class="form-label" for="input-smoothing">Smoothing</label>
                            <input class="form-input" id="input-smoothing" name="smoothing" type="number" value="8" step="0.01" />
                            <p class="form-input-hint">Only keep the points that are at least at this distance (in meters) from their predecessor.</p>
                        </div>
                        <div class="form-group">
                            <label class="form-label" for="input-simplification">Simplification</label>
                            <input class="form-input" id="input-simplification" name="simplification" type="number" value="0.6" step="0.01" />
                            <p class="form-input-hint">Proportion of points to keep in the created track.</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary">Create a smooth track</button>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        {% if track.is_route %}
        mapWrapper.bindButtonClearTrack("buttonClearTrack");
        {% endif %}
        mapWrapper.bindButtonSaveTrack("buttonSaveTrack");
        mapWrapper.bindTrackForm("track_form");
        document.querySelector("#track_form input[name='label']").value = "{{ track.label | safe }}";
        document.querySelector("#track_form textarea[name='comment']").value = "{{ track.comment | safe }}";
    </script>

</div>
{% endblock main_content %}

topopartner/templates/topopartner/home.html
{% extends 'topopartner/base.html' %}
{% load static %}

{% block title %}Home &mid; {{ block.super }}{% endblock title %}

{% block main_content %}

<div class="h1">Topopartner</div>

<p>
    <b>Topopartner</b> is a Django application dedicated to topographic personal data management.
    Namely, it holds a database of <b>waypoints</b> and <b>tracks</b>.
    It offers a track edition interface, GPX exports, elevation profile plots, hike duration prediction, and more.
    It greatly relies on the
    <span class="highlight"><a href="https://leafletjs.com/">Leaflet</a></span>
    library,
    <span class="highlight"><a href="https://wiki.openstreetmap.org/wiki/OpenTopoMap">OpenTopoMap</a></span>
    maps, and
    <span class="highlight"><a href="https://www.gpsvisualizer.com/">GPS Visualizer</a></span>
    features.
</p>

<p>
    It is available on <a href="https://github.com/ychalier/topopartner">GitHub</a>.
    If you want to try it yourself, <a href="https://chalier.fr/#contact">contact me</a> for a demo account.
</p>

{% endblock main_content %}

topopartner/templates/topopartner/itineraries.html
{% extends 'topopartner/layout/base.html' %}
{% load mathfilters %}
{% load static %}

{% block title %}Itineraries &mid; {{ block.super }}{% endblock title %}

{% block head %}
{{ block.super }}
<script src="{% static 'topopartner/js/map.js' %}"></script>
{% endblock head %}

{% block main_content %}

{% if itineraries %}

<div class="tab-container">

    <ul class="tab">
        <li class="tab-item"><a for="tab-grid">Grid</a></li>
        <li class="tab-item"><a for="tab-table">Table</a></li>
        <li class="tab-item tab-action">
            <div class="input-group input-inline">
                <a class="btn btn-primary btn-sm input-group-btn" href="{% url 'topopartner:create_track' %}" title="Create an itinerary">Create</a>
            </div>
        </li>
    </ul>

    <div class="tab-content" id="tab-grid" style="overflow-x: hidden">
        <div class="columns">
            {% for track in itineraries %}
            <div class="column col-6 col-sm-12">
                {% include 'topopartner/partials/map_card.html' %}
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="tab-content" id="tab-table">
        <table class="table table-striped table-hover">
            <tr>
                <th>Label</th>
                <th>Distance</th>
                <th>Uphill</th>
                <th>Downhill</th>
                <th title="Estimated duration based on recorded tracks.">Duration&lowast;</th>
                <th>Creation</th>
                <th>Public</th>
            </tr>
            {% for track in itineraries %}
            <tr>
                <td class="highlight"><a class="transparent" href="{% url 'topopartner:view_track' tid=track.id%}">{{ track.label }}</a></td>
                <td>{% if track.distance %}{{ track.distance | mul:.001 | floatformat }}km{% else %}&mdash;{% endif %}</td>
                <td>{% if track.uphill %}{{ track.uphill | floatformat:"0" }}m{% else %}&mdash;{% endif %}</td>
                <td>{% if track.downhill %}{{ track.downhill | floatformat:"0" }}m{% else %}&mdash;{% endif %}</td>
                <td>{% if track.duration %}{{ track.pretty_duration }}{% else %}&mdash;{% endif %}</td>
                <td>{{ track.date_added | date }}</td>
                <td>{% if track.public %}&check;{% else %}&mdash;{% endif %}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

</div>

{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-4x icon-route"></i>
    </div>
    <p class="empty-title h5">Empty</p>
    <p class="empty-subtitle">Click the button below to create your first itinerary.</p>
    <div class="empty-action">
        <a class="btn btn-primary" href="{% url 'topopartner:create_track' %}">Create itinerary</a>
    </div>
</div>
{% endif %}

{% include 'topopartner/partials/api_key.html' %}

{% endblock main_content %}

topopartner/templates/topopartner/map.html
{% load static %}

<script type="text/javascript" src="{% static 'topopartner/js/map.js' %}"></script>

<template id="template_marker_popup">
    <div class="marker_popup">
        <small><b>Label</b></small>
        <input type="text" name="label" value="" placeholder="Waypoint's label" />
        <small><b>Comment</b></small>
        <input type="text" name="comment" value="" placeholder="Description" />
        <small><b>Elevation</b></small>
        <input type="number" name="elevation" placeholder="Elevation" value="" step="any" />
        <small><b>Category</b></small>
        <select name="category">
            {% for category in mapdata.categories %}
            <option value="-1">None</option>
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        Visited <input type="checkbox" name="visited" placeholder="Visited" />
        <button type="button" name="delete">Delete</button>
    </div>
</template>

<template id="template_polyline_panel">
    <div class="polyline">
        <span class="polyline_label"></span>
        <button class="cmd_button" type="button" name="remove">Remove</button>
        <button class="cmd_button" type="button" name="save">Save</button>
    </div>
</template>

<div class="map" id="map"></div>

<script type="text/javascript">{% include 'topopartner/map.js' %}</script>

topopartner/templates/topopartner/map_card.html
{% load mathfilters %}

<div class="card my-2 {% if track.is_itinerary %}{% else %}{% endif %}">
    <div class="card-illustration">
        <a href="{% url 'topopartner:view_track' tid=track.id %}">
            <div class="still-map video-responsive" id="still-map-{{ track.id }}" route="{% url 'topopartner:get_trackpoints' tid=track.id %}" }}"></div>
        </a>
    </div>
    <div class="card-header">
        <div class="card-title h5">{{ track.label }}</div>
        <div class="card-subtitle text-gray">
            {% if track.is_recording %} Recorded on {{ track.date_visited }} {% endif %}
        </div>
    </div>
    <div class="card-body">
        <div class="d-flex">
            <div><i class="icon icon-route"></i>{{ track.distance | mul:.001 | floatformat }}km &nbsp;</div>
            <div><i class="icon icon-terrain"></i>{{ track.uphill | floatformat:"0" }}m &nbsp;</div>
            <div><i class="icon icon-timer"></i>{{ track.pretty_duration }} {% if track.public %} &nbsp;</div>
            <div><i class="icon icon-unlock" title="This track is public."></i> Public {% endif %}</div>
        </div>
    </div>
    <div class="card-footer">
        <a class="btn btn-primary" href="{% url 'topopartner:view_track' tid=track.id %}">View</a>
        <a class="btn btn-link" href="{% url 'topopartner:edit_track' tid=track.id %}">Edit</a>
        <a class="btn btn-link" href="{% url 'topopartner:gpx' tid=track.id %}">Download</a>
    </div>
</div>

topopartner/templates/topopartner/recordings.html
{% extends 'topopartner/layout/base.html' %}
{% load mathfilters %}
{% load static %}

{% block title %}Recordings &mid; {{ block.super }}{% endblock title %}

{% block head %}
{{ block.super }}
<script src="{% static 'topopartner/js/map.js' %}"></script>
{% endblock head %}

{% block main_content %}

{% if recordings %}

<div class="tab-container">

    <ul class="tab">
        <li class="tab-item"><a for="tab-grid">Grid</a></li>
        <li class="tab-item"><a for="tab-table">Table</a></li>
        <li class="tab-item tab-action">
            <div class="input-group input-inline">
                <a class="btn btn-primary btn-sm input-group-btn" href="{% url 'topopartner:upload_track' %}" title="Upload a recorded GPX track">Upload</a>
                <a class="btn btn-primary btn-sm input-group-btn" href="{% url 'topopartner:fit' %}" title="Fit the linear regression model for predicting duration on those recorded tracks.">Fit</a>
            </div>
        </li>
    </ul>

    <div class="tab-content" id="tab-grid" style="overflow-x: hidden">
        <div class="columns">
            {% for track in recordings %}
            <div class="column col-6 col-sm-12">
                {% include 'topopartner/partials/map_card.html' %}
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="tab-content" id="tab-table">
        <table class="table table-striped table-hover">
            <tr>
                <th>Label</th>
                <th>Distance</th>
                <th>Uphill</th>
                <th>Downhill</th>
                <th>Duration</th>
                <th>Date</th>
                <th>Public</th>
            </tr>
            {% for track in recordings %}
            <tr>
                <td class="highlight"><a class="transparent" href="{% url 'topopartner:view_track' tid=track.id%}">{{ track.label }}</a></td>
                <td>{% if track.distance %}{{ track.distance | mul:.001 | floatformat }}km{% else %}&mdash;{% endif %}</td>
                <td>{% if track.uphill %}{{ track.uphill | floatformat:"0" }}m{% else %}&mdash;{% endif %}</td>
                <td>{% if track.downhill %}{{ track.downhill | floatformat:"0" }}m{% else %}&mdash;{% endif %}</td>
                <td>{% if track.duration %}{{ track.pretty_duration }}{% else %}&mdash;{% endif %}</td>
                <td>{{ track.date_visited }}</td>
                <td>{% if track.public %}&check;{% else %}&mdash;{% endif %}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

</div>

<h2>Current model</h2>

<pre>Duration (s) = <span class="highlight">{{ linreg.intercept | floatformat }}</span> &plus; <span class="highlight">{{ linreg.coef_distance | floatformat }}</span> &times; Distance (m) &plus; <span class="highlight">{{ linreg.coef_uphill | floatformat }}</span> &times; Uphill (m)</pre>

{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-4x icon-route"></i>
    </div>
    <p class="empty-title h5">Empty</p>
    <p class="empty-subtitle">Click the button below to upload your first recording.</p>
    <div class="empty-action">
        <a class="btn btn-primary" href="{% url 'topopartner:upload_track' %}">Upload track</a>
    </div>
</div>
{% endif %}

{% include 'topopartner/partials/api_key.html' %}

{% endblock main_content %}

topopartner/templates/topopartner/routes.html
{% extends 'topopartner/layout/base.html' %}
{% load mathfilters %}
{% load static %}

{% block title %}Routes &mid; {{ block.super }}{% endblock title %}

{% block head %}
{{ block.super }}
<script src="{% static 'topopartner/js/map.js' %}"></script>
{% endblock head %}

{% block main_content %}

{% if routes %}

<div class="tab-container">

    <ul class="tab">
        <li class="tab-item"><a for="tab-grid">Grid</a></li>
        <li class="tab-item"><a for="tab-table">Table</a></li>
        <li class="tab-item tab-action">
            <div class="input-group input-inline">
                <a class="btn btn-primary btn-sm input-group-btn" href="{% url 'topopartner:create_track' %}" title="Create a route">Create</a>
            </div>
        </li>
    </ul>

    <div class="tab-content" id="tab-grid" style="overflow-x: hidden">
        <div class="columns">
            {% for track in routes %}
            <div class="column col-6 col-sm-12">
                {% include 'topopartner/partials/map_card.html' %}
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="tab-content" id="tab-table">
        <table class="table table-striped table-hover">
            <tr>
                <th>Label</th>
                <th>Distance</th>
                <th>Uphill</th>
                <th>Downhill</th>
                <th title="Estimated duration based on recorded tracks.">Duration&lowast;</th>
                <th>Creation</th>
                <th>Public</th>
            </tr>
            {% for track in routes %}
            <tr>
                <td class="highlight"><a class="transparent" href="{% url 'topopartner:view_track' tid=track.id%}">{{ track.label }}</a></td>
                <td>{% if track.distance %}{{ track.distance | mul:.001 | floatformat }}km{% else %}&mdash;{% endif %}</td>
                <td>{% if track.uphill %}{{ track.uphill | floatformat:"0" }}m{% else %}&mdash;{% endif %}</td>
                <td>{% if track.downhill %}{{ track.downhill | floatformat:"0" }}m{% else %}&mdash;{% endif %}</td>
                <td>{% if track.duration %}{{ track.pretty_duration }}{% else %}&mdash;{% endif %}</td>
                <td>{{ track.date_added | date }}</td>
                <td>{% if track.public %}&check;{% else %}&mdash;{% endif %}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

</div>

{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-4x icon-route"></i>
    </div>
    <p class="empty-title h5">Empty</p>
    <p class="empty-subtitle">Click the button below to create your first route.</p>
    <div class="empty-action">
        <a class="btn btn-primary" href="{% url 'topopartner:create_track' %}">Create route</a>
    </div>
</div>
{% endif %}

{% include 'topopartner/partials/api_key.html' %}

{% endblock main_content %}

topopartner/templates/topopartner/track.html
{% extends 'topopartner/layout/base.html' %}
{% load mathfilters %}
{% load static %}

{% block title %}{{ track.label }} &mid; Tracks &mid; {{ block.super }}{% endblock title %}

{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'topopartner/css/map.css' %}">
<link rel="stylesheet" href="{% static 'topopartner/css/track.css' %}">
{% endblock head %}

{% block main_content %}

<h1>{{ track.label }}</h1>

<div class="columns">

    <div class="column col-8 col-sm-12">
        {% include 'topopartner/partials/map.html' %}
    </div>

    <div class="column col-4 col-sm-12">
        <div class="track_info__content">
            <canvas id="elevation_profile" width="600" height="300"></canvas>
            <div>
                <div class="my-2">
                    <div>
                        <span class="track-info-icon"><i class="icon icon-run-circle" title="Walked distance"></i></span>
                        <span class="track-info-number">{% if track.distance %}{{ track.distance | mul:.001 | floatformat }}{% else %}&ndash;&ndash;{% endif %}</span>
                        <span class="track-info-unit">km</span>
                    </div>
                    <div>
                        <span class="track-info-icon"><i class="icon icon-terrain"></i></span>
                        <span class="track-info-number">{% if track.uphill %}{{ track.uphill | floatformat:"0" }}{% else %}&ndash;&ndash;{% endif %}</span>
                        <span class="track-info-unit">m</span>
                    </div>
                    <div>
                        {% if track.is_route %}
                        <span class="track-info-icon"><i class="icon icon-history-toggle-off"></i></span>
                        {% else %}
                        <span class="track-info-icon"><i class="icon icon-timer"></i></span>
                        {% endif %}
                        <span class="track-info-number">{% if track.duration %}{{ track.pretty_duration }}{% else %}&ndash;&ndash;{% endif %}</span>
                    </div>
                    <div>
                        <a href="https://www.google.com/maps/dir//{{ track.start.latitude }}%2C{{ track.start.longitude }}" title="Car directions">
                            <span class="track-info-icon"><i class="icon icon-directions-car"></i></span>
                            Car directions
                        </a>
                    </div>
                    <div>
                        <a href="{% url 'topopartner:download_track_gpx' tid=track.id %}" title="Download GPX file">
                            <span class="track-info-icon" ><i class="icon icon-map"></i></span>
                            Download GPX
                        </a>
                    </div>
                    <div>
                        <a href="{% url 'topopartner:download_track_stl' tid=track.id %}" title="Download STL file">
                            <span class="track-info-icon" ><i class="icon icon-download"></i></span>
                            Download STL
                        </a>
                    </div>
                </div>
                {% if track.comment %}
                <p>
                    {{ track.comment | safe }}
                </p>
                {% endif %}
                {% if track.date_visited %}
                <p>
                    Recorded on {{ track.date_visited }}.
                </p>
                {% endif %}
                {% if request.user == track.user %}
                <p>
                    <a class="btn btn-primary" href="{% url 'topopartner:edit_track' tid=track.id %}">Edit</a>
                </p>
                {% endif %}
            </div>
            <script type="text/javascript" src="{% static 'topopartner/js/elevation.js' %}"></script>
            <script type="text/javascript">
                let ctx = document.getElementById("elevation_profile").getContext('2d');
                let data = [{% for d, e in elevation_data %}{x: {{d|floatformat:0}}, y: {{e|floatformat:0}} }, {% endfor %}];
                createElevationProfile(ctx, data);
            </script>
        </div>
    </div>
</div>
{% endblock main_content %}

{% block side_content %}

{% endblock side_content %}

topopartner/templates/topopartner/upload.html
{% extends 'topopartner/layout/base.html' %}

{% block title %}Upload a track &mid; {{ block.super }}{% endblock title %}

{% block main_content %}

<h1>Upload a track</h1>
<form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    
    <div class="form-group">
        <label class="form-label" for="input-label">Label</label>
        <input class="form-input" id="input-label" type="text" name="label" placeholder="Label" />
    </div>

    <div class="form-group">
        <label class="form-label" for="input-comment">Comment</label>
        <textarea class="form-input" id="input-comment" name="comment" rows="8" cols="80" placeholder="Comment"></textarea>
    </div>

    <div class="form-group">
        <label class="form-label" for="input-file">GPX File</label>
        <input class="form-input" id="input-file" type="file" name="gpx" />
    </div>

    <div class="form-group">
        <label class="form-switch">
            <input id="checkbox" type="checkbox" name="route"/>
            <i class="form-icon"></i> Is route
        </label>
    </div>

    <div class="form-group">
        <label class="form-label" for="input-visited">Date visited</label>
        <input class="form-input" id="input-visited" type="date" name="visited" placeholder="Date visited"/>
    </div>

    <div class="form-group">
        <button class="btn btn-primary">Upload</button>
    </div>

</form>

{% endblock %}