topopartner/urls.py
from django.urls import path
from . import views

app_name = "topopartner"

urlpatterns = [
    path("", views.view_landing, name="landing"),
    path("about", views.view_about, name="about"),
    path("routes", views.view_routes, name="routes"),
    path("recordings", views.view_recordings, name="recordings"),
    path("track/create", views.view_create_track, name="create_track"),
    path("track/upload", views.view_upload_track, name="upload_track"),
    path("track/<tid>", views.view_track, name="view_track"),
    path("track/<tid>/edit", views.view_edit_track, name="edit_track"),
    path("track/<tid>/elevate", views.view_elevate_track, name="elevate_track"),
    path("track/<tid>/smooth", views.view_smooth_track, name="smooth_track"),
    path("track/<tid>/download", views.view_download_track, name="download_track"),
    path("track/<tid>/download/gpx", views.view_download_track_gpx, name="download_track_gpx"),
    path("track/<tid>/download/stl", views.view_download_track_stl, name="download_track_stl"),
    path("track/<tid>/delete", views.view_delete_track, name="delete_track"),
    path("track/<tid>/points", views.view_track_points, name="track_points"),
    path("fit", views.view_fit, name="fit"),
    path("api/route/list", views.api_list_routes, name="api_list_routes"),
    path("api/route/get", views.api_get_route, name="api_get_route"),
    path("api/recording/post", views.api_post_recording, name="api_post_recording"),
]

topopartner/templates/topopartner/partials/api_key.html
{% if api_key %}
<div class="input-group censor-container">
    <span class="input-group-addon"><a href="https://github.com/ychalier/topopartner-android">Android</a> API Key</span>
    <input class="form-input censor-input" type="password" value="{{ api_key.key }}" disabled />
    <button class="input-group-btn btn btn-primary censor-button">Show</button>
</div>
{% else %}
<p>
    You do not have an <a href="https://github.com/ychalier/topopartner-android">Android</a> API Key. If you think you should, please contact an admin.
</p>
{% endif %}

topopartner/templates/topopartner/partials/map.html
{% load static %}

<script type="text/javascript" src="{% static 'topopartner/js/map.js' %}"></script>

<template id="template_marker_popup">
    <div class="marker_popup">
        <small><b>Label</b></small>
        <input type="text" name="label" value="" placeholder="Waypoint's label" />
        <small><b>Comment</b></small>
        <input type="text" name="comment" value="" placeholder="Description" />
        <small><b>Elevation</b></small>
        <input type="number" name="elevation" placeholder="Elevation" value="" step="any" />
        <small><b>Category</b></small>
        <select name="category">
            {% for category in mapdata.categories %}
            <option value="-1">None</option>
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        Visited <input type="checkbox" name="visited" placeholder="Visited" />
        <button type="button" name="delete">Delete</button>
    </div>
</template>

<template id="template_polyline_panel">
    <div class="polyline">
        <span class="polyline_label"></span>
        <button class="cmd_button" type="button" name="remove">Remove</button>
        <button class="cmd_button" type="button" name="save">Save</button>
    </div>
</template>

<div class="map" id="map"></div>

<script type="text/javascript">
var mapWrapper = new MapWrapper();
mapWrapper.defaultView.center.latitude = {{ mapdata.center.lat }};
mapWrapper.defaultView.center.longitude = {{ mapdata.center.lng }};
{% if not mapdata.track %}
mapWrapper.defaultView.bounds.southwest = {{ mapdata.bounds.sw }};
mapWrapper.defaultView.bounds.northeast = {{ mapdata.bounds.ne }};
{% endif %}
mapWrapper.createLeafletMap("map");
{% if mapdata.edit == 'marker' %}
mapWrapper.appendAddMarkerControl();
{% endif %}
{% if mapdata.edit == 'polyline' %}
mapWrapper.appendAddPolylineControl();
{% endif %}
{% if mapdata.track %}
var trackWrapper = new Track(mapWrapper);
trackWrapper.latlngs = [{% for lat, lon in mapdata.track %}[{{ lat }}, {{ lon }}]{% if forloop.last %}{% else %}, {% endif %}{% endfor %}];
trackWrapper.createLeafletPolyline({% if mapdata.edit == 'polyline' %}true{% else %}false{% endif %}, true);
mapWrapper.leaflet.fitBounds(trackWrapper.leaflet.getBounds());
{% endif %}
setTimeout(function(){ mapWrapper.leaflet.invalidateSize()}, 400);
</script>

topopartner/templates/topopartner/partials/map_card.html
{% load mathfilters %}

<div class="card my-2 {% if track.is_route %}{% else %}{% endif %}">
    <div class="card-illustration">
        <a href="{% url 'topopartner:view_track' tid=track.id %}">
            <div class="still-map video-responsive" id="still-map-{{ track.id }}" href="{% url 'topopartner:track_points' tid=track.id %}"></div>
        </a>
    </div>
    <div class="card-header">
        <div class="card-title h5">{{ track.label }}</div>
        <div class="card-subtitle text-gray">
            {% if track.is_recording %} Recorded on {{ track.date_visited }} {% endif %}
        </div>
    </div>
    <div class="card-body">
        <div class="d-flex">
            <div><i class="icon icon-route"></i>{{ track.distance | mul:.001 | floatformat }}km &nbsp;</div>
            <div><i class="icon icon-terrain"></i>{{ track.uphill | floatformat:"0" }}m &nbsp;</div>
            <div><i class="icon icon-timer"></i>{{ track.pretty_duration }} {% if track.public %} &nbsp;</div>
            <div><i class="icon icon-unlock" title="This track is public."></i> Public {% endif %}</div>
        </div>
    </div>
    <div class="card-footer">
        <a class="btn btn-primary" href="{% url 'topopartner:view_track' tid=track.id %}">View</a>
        <a class="btn btn-link" href="{% url 'topopartner:edit_track' tid=track.id %}">Edit</a>
        <a class="btn btn-link" href="{% url 'topopartner:download_track_gpx' tid=track.id %}">Download</a>
    </div>
</div>